"""empty message

Revision ID: 84438ee89894
Revises: 
Create Date: 2021-06-03 00:18:01.345958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84438ee89894'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('pd_rep', sa.Boolean(), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('jurisdictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('pd_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pd_id'], ['pds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reflections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post', sa.Text(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pd_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pd_id'], ['pds.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reflection_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['reflection_id'], ['reflections.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    op.drop_table('reflections')
    op.drop_table('jurisdictions')
    op.drop_table('users')
    op.drop_table('pds')
    # ### end Alembic commands ###
